"""rol y autoaprobado en bitacora

Revision ID: 367f59929fad
Revises: 9224e8a61ad0
Create Date: 2026-09-30 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367f59929fad'
down_revision: Union[str, None] = '9224e8a61ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bitacora', sa.Column('rol', sa.String(length=20), nullable=True))
    op.add_column(
        'bitacora',
        sa.Column(
            'autoaprobado', sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bitacora', 'autoaprobado')
    op.drop_column('bitacora', 'rol')
    # ### end Alembic commands ###
