"""agregar periodo_cierre a analisis

Revision ID: 7236da454602
Revises: ab2dd1e9f229
Create Date: 2026-09-25 09:21:24.800125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7236da454602'
down_revision: Union[str, None] = 'ab2dd1e9f229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analisis', sa.Column('periodo_cierre', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analisis', 'periodo_cierre')
    # ### end Alembic commands ###
