"""autenticacion y permisos (P-12)

Revision ID: 7a01fd7275ed
Revises: c3f7a1d9e824
Create Date: 2026-10-09 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a01fd7275ed'
down_revision: Union[str, None] = 'c3f7a1d9e824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column(
        'usuario',
        sa.Column(
            'debe_cambiar_password', sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        'usuario',
        sa.Column('intentos_fallidos', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'usuario', sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        'usuario', sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True)
    )
    op.create_unique_constraint(
        'ux_permiso_rol_recurso_accion', 'permiso', ['rol_id', 'recurso', 'accion']
    )
    op.create_index('ix_analisis_fecha_inicio', 'analisis', ['fecha_inicio'])
    op.create_index(
        'ix_documento_usuario_carga_area', 'documento', ['usuario_carga_id', 'area_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documento_usuario_carga_area', table_name='documento')
    op.drop_index('ix_analisis_fecha_inicio', table_name='analisis')
    op.drop_constraint('ux_permiso_rol_recurso_accion', 'permiso', type_='unique')
    op.drop_column('usuario', 'ultimo_acceso')
    op.drop_column('usuario', 'bloqueado_hasta')
    op.drop_column('usuario', 'intentos_fallidos')
    op.drop_column('usuario', 'debe_cambiar_password')
    op.drop_column('usuario', 'password_hash')
    # ### end Alembic commands ###
