"""esquema inicial

Revision ID: 7eab2d96069e
Revises: 
Create Date: 2026-09-24 18:56:30.907692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eab2d96069e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_revision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('permiso',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('recurso', sa.String(length=100), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('origen_autenticacion', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bitacora',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre_original', sa.String(length=500), nullable=False),
    sa.Column('tipo_archivo', sa.String(length=20), nullable=False),
    sa.Column('tamano_bytes', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_carga_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.Column('fecha_expiracion', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['usuario_carga_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuente_conocimiento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('curador_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['curador_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analisis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('documento_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_revision_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('modelo_llm', sa.String(length=200), nullable=True),
    sa.Column('version_prompt', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.ForeignKeyConstraint(['tipo_revision_id'], ['tipo_revision.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fragmento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fuente_id', sa.Uuid(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('referencia_vector', sa.String(length=100), nullable=True),
    sa.Column('pagina_o_seccion', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuente_conocimiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glosario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('termino', sa.String(length=200), nullable=False),
    sa.Column('definicion', sa.Text(), nullable=False),
    sa.Column('fuente_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuente_conocimiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regla',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=20), nullable=True),
    sa.Column('severidad', sa.String(length=10), nullable=True),
    sa.Column('fuente_id', sa.Uuid(), nullable=True),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuente_conocimiento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('version_documento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('documento_id', sa.Uuid(), nullable=False),
    sa.Column('numero_version', sa.Integer(), nullable=False),
    sa.Column('ruta_almacenamiento', sa.String(length=1000), nullable=False),
    sa.Column('es_corregida', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hallazgo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analisis_id', sa.Uuid(), nullable=False),
    sa.Column('version_documento_id', sa.Uuid(), nullable=False),
    sa.Column('regla_id', sa.Uuid(), nullable=True),
    sa.Column('fragmento_id', sa.Uuid(), nullable=True),
    sa.Column('severidad', sa.String(length=10), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('correccion_sugerida', sa.Text(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis.id'], ),
    sa.ForeignKeyConstraint(['fragmento_id'], ['fragmento.id'], ),
    sa.ForeignKeyConstraint(['regla_id'], ['regla.id'], ),
    sa.ForeignKeyConstraint(['version_documento_id'], ['version_documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hallazgo_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('resultado', sa.String(length=20), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hallazgo_id'], ['hallazgo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision')
    op.drop_table('hallazgo')
    op.drop_table('version_documento')
    op.drop_table('regla')
    op.drop_table('glosario')
    op.drop_table('fragmento')
    op.drop_table('analisis')
    op.drop_table('fuente_conocimiento')
    op.drop_table('documento')
    op.drop_table('bitacora')
    op.drop_table('usuario')
    op.drop_table('permiso')
    op.drop_table('tipo_revision')
    op.drop_table('rol')
    op.drop_table('area')
    # ### end Alembic commands ###
