"""agregar texto_original a hallazgo

Revision ID: a1c4e7f9b2d3
Revises: fda3344d7bdc
Create Date: 2026-10-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c4e7f9b2d3'
down_revision: Union[str, None] = 'fda3344d7bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hallazgo', sa.Column('texto_original', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hallazgo', 'texto_original')
    # ### end Alembic commands ###
