"""ampliar hallazgo.moneda a varchar(10)

Revision ID: ab2dd1e9f229
Revises: 7eab2d96069e
Create Date: 2026-09-25 09:10:23.474137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2dd1e9f229'
down_revision: Union[str, None] = '7eab2d96069e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hallazgo', 'moneda',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hallazgo', 'moneda',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)
    # ### end Alembic commands ###
