"""tipo_documento y accion en analisis (CU-02)

Revision ID: c3f7a1d9e824
Revises: 367f59929fad
Create Date: 2026-10-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f7a1d9e824'
down_revision: Union[str, None] = '367f59929fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analisis', sa.Column('tipo_documento', sa.String(length=20), nullable=True))
    op.add_column('analisis', sa.Column('accion', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analisis', 'accion')
    op.drop_column('analisis', 'tipo_documento')
    # ### end Alembic commands ###
