"""totales del analisis y fuente citada del hallazgo

Revision ID: fda3344d7bdc
Revises: 9b697bc5b53e
Create Date: 2026-09-25 14:26:20.438292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda3344d7bdc'
down_revision: Union[str, None] = '9b697bc5b53e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analisis', sa.Column('total_debe', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('analisis', sa.Column('total_haber', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('analisis', sa.Column('moneda', sa.String(length=10), nullable=True))
    op.add_column('hallazgo', sa.Column('fuente_citada', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hallazgo', 'fuente_citada')
    op.drop_column('analisis', 'moneda')
    op.drop_column('analisis', 'total_haber')
    op.drop_column('analisis', 'total_debe')
    # ### end Alembic commands ###
