/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/iniciar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar Carga */
        post: operations["iniciar_carga_documentos_iniciar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/partes/{numero_parte}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Subir Parte Documento */
        put: operations["subir_parte_documento_documentos__documento_id__partes__numero_parte__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/partes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Partes Subidas Documento
         * @description RN-09: permite reanudar una carga interrumpida preguntando qué partes
         *     ya llegaron a S3, en vez de volver a subir el archivo completo.
         */
        get: operations["listar_partes_subidas_documento_documentos__documento_id__partes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/completar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Completar Carga */
        post: operations["completar_carga_documentos__documento_id__completar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analisis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Analisis
         * @description Panel de "análisis recientes": del área del usuario, o de todas para
         *     Administrador/Auditor (mismo criterio que consultar_analisis).
         */
        get: operations["listar_analisis_analisis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analisis/{analisis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar Analisis */
        get: operations["consultar_analisis_analisis__analisis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analisis/{analisis_id}/hallazgos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Hallazgos */
        get: operations["listar_hallazgos_analisis__analisis_id__hallazgos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analisis/{analisis_id}/mejorar-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mejorar Redaccion Stream
         * @description Fase 2 de CU-02 (RF-07, RF-12): LLM por párrafo con streaming SSE, uno
         *     por párrafo, apenas está listo -- ver
         *     docs/02-analisis/02-analisis-cu02-redaccion-amigable.md §2.1. Corre
         *     síncrona dentro de esta misma conexión HTTP porque no hay un worker
         *     Celery que pueda empujar eventos a una conexión ya abierta (primer
         *     endpoint de streaming de toda la API). Se autentica con el mismo Bearer
         *     de siempre -- a propósito no es un token por query param -- así que el
         *     frontend debe consumirlo con `fetch` + lector de stream, no con
         *     `EventSource` nativo (que no manda headers).
         */
        get: operations["mejorar_redaccion_stream_analisis__analisis_id__mejorar_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analisis/{analisis_id}/bitacora": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Bitacora Analisis
         * @description Pantalla "Agente trabajando" (U3): registro de pasos del análisis.
         *     Hoy solo hay 'analisis_iniciado'/'analisis_completado' (ver
         *     orquestador/tareas.py) — el pipeline no emite eventos más granulares
         *     todavía.
         */
        get: operations["listar_bitacora_analisis_analisis__analisis_id__bitacora_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hallazgos/{hallazgo_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decidir Hallazgo */
        post: operations["decidir_hallazgo_hallazgos__hallazgo_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analisis/{analisis_id}/generar-corregido": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generar Corregido
         * @description RF-14 (CU-05): aplica solo los hallazgos ya "aceptados" (CU-07) sobre
         *     el documento original y sube el resultado como nueva `VersionDocumento`
         *     corregida. A diferencia de CU-01, esto no ocurre automáticamente durante
         *     el análisis -- el Revisor lo dispara explícitamente después de decidir
         *     (docs/03-diseno/secuencia/cu-05-ortografia.md, supuesto 4). Sin LLM de
         *     por medio (las correcciones ya están decididas), se hace síncrono.
         */
        post: operations["generar_corregido_analisis__analisis_id__generar_corregido_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reportes/ajustes-autoaprobados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Ajustes Autoaprobados
         * @description SRS v0.9 (RG-06, PP-09): ajustes de CU-01 (contable) que el mismo
         *     usuario que cargó el documento decidió sobre sí mismo -- visible para
         *     Administrador/Auditor ("Jefatura" no es un rol propio del sistema hoy;
         *     se cubre con Administrador). Construido directamente sobre la bitácora
         *     (Bitacora.autoaprobado, que deja decidir_hallazgo), no sobre Decision:
         *     así el reporte es literalmente "lo que quedó en el registro", en línea
         *     con el nuevo umbral de PP-09 ("0 aprobaciones sin registro"). Se filtra
         *     por correo (no por id) -- es lo que Jefatura/Auditor realmente conoce
         *     del usuario, no hay pantalla de "buscar usuario por UUID".
         */
        get: operations["listar_ajustes_autoaprobados_reportes_ajustes_autoaprobados_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fuentes-conocimiento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Fuentes Conocimiento
         * @description RF-16: fuentes vigentes del área del usuario, para que elija cuáles
         *     consultar al iniciar un análisis (ver ADR-002, estado=vigente).
         */
        get: operations["listar_fuentes_conocimiento_fuentes_conocimiento_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/version-corregida": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Descargar Version Corregida
         * @description Descarga la versión corregida del documento -- el Excel con celdas
         *     marcadas de CU-01 (validadores.contable.salida) o el documento con el
         *     texto ya corregido de CU-05 (ortografia.generar_corregido). La API hace
         *     de intermediaria en vez de dar un enlace directo a LocalStack/MinIO
         *     porque ese endpoint interno (`localstack:4566`) no es alcanzable desde
         *     el navegador.
         */
        get: operations["descargar_version_corregida_documentos__documento_id__version_corregida_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curaduria/fuentes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Fuentes Curaduria
         * @description Curador ve las fuentes (todas las versiones/estados) de su área;
         *     Administrador y Auditor, de todas las áreas -- solo lectura.
         */
        get: operations["listar_fuentes_curaduria_curaduria_fuentes_get"];
        put?: never;
        /**
         * Crear Fuente
         * @description Registra una fuente nueva (o una nueva versión de una existente,
         *     mismo fuente_id) como "borrador" -- nunca queda vigente hasta que el
         *     propio curador la aprueba (POST .../aprobar).
         */
        post: operations["crear_fuente_curaduria_fuentes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curaduria/fuentes/{fuente_id}/vista-previa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vista Previa Fuente
         * @description Extrae los fragmentos (por sección/página) del archivo YA CARGADO de
         *     la fuente, sin indexar nada -- para que el curador revise antes de
         *     aprobar. No aplica a las fuentes que vienen de una hoja de la
         *     plantilla (Catálogo/Glosario/Checklist): esas no tienen un archivo
         *     propio, ya están en tablas estructuradas.
         */
        get: operations["vista_previa_fuente_curaduria_fuentes__fuente_id__vista_previa_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curaduria/fuentes/{fuente_id}/aprobar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aprobar Fuente Endpoint
         * @description Aprueba la fuente como vigente (curaduria.fuentes.aprobar_fuente --
         *     obsoletea automáticamente cualquier versión vigente anterior del mismo
         *     fuente_id) y la indexa (curaduria.indexacion.indexar_fuente: extrae,
         *     calcula embeddings, guarda en Qdrant, mide y registra el tiempo). Todo
         *     en una sola transacción: si la indexación falla (p. ej. PDF sin
         *     texto), la aprobación tampoco queda.
         */
        post: operations["aprobar_fuente_endpoint_curaduria_fuentes__fuente_id__aprobar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curaduria/fuentes/{fuente_id}/marcar-obsoleta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Marcar Fuente Obsoleta
         * @description Retira una fuente vigente sin reemplazarla por una versión nueva
         *     (a diferencia de aprobar_fuente, que obsoletea automáticamente al
         *     aprobar la siguiente) -- p. ej. un documento que dejó de aplicar. Sus
         *     fragmentos en Qdrant se desactivan (payload, no se borran -- RNF-06).
         */
        post: operations["marcar_fuente_obsoleta_curaduria_fuentes__fuente_id__marcar_obsoleta_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curaduria/glosario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Glosario Curaduria */
        get: operations["listar_glosario_curaduria_curaduria_glosario_get"];
        put?: never;
        /** Crear Termino Glosario */
        post: operations["crear_termino_glosario_curaduria_glosario_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curaduria/glosario/{termino_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Eliminar Termino Glosario */
        delete: operations["eliminar_termino_glosario_curaduria_glosario__termino_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curaduria/plantilla/validar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validar Plantilla Endpoint
         * @description Lee y valida la plantilla SIN persistir nada (RF-16, Bloque K2/K5) --
         *     reporta todos los errores encontrados, de todas las hojas.
         */
        post: operations["validar_plantilla_endpoint_curaduria_plantilla_validar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curaduria/plantilla/importar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Importar Plantilla Endpoint
         * @description Valida y, si no hay ningún error, carga la plantilla completa como
         *     "borrador" (curaduria.plantilla.cargar_plantilla) -- nunca carga nada
         *     parcial: si hay errores, no se persiste nada y se devuelve el reporte.
         */
        post: operations["importar_plantilla_endpoint_curaduria_plantilla_importar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AjusteAutoaprobadoEsquema
         * @description SRS v0.9 (RG-06, PP-09): una fila del reporte "Ajustes autoaprobados"
         *     -- un hallazgo de CU-01 (contable) que el mismo usuario que cargó el
         *     documento decidió sobre sí mismo.
         */
        AjusteAutoaprobadoEsquema: {
            /**
             * Fecha Hora
             * Format: date-time
             */
            fecha_hora: string;
            /** Usuario Email */
            usuario_email: string;
            /** Usuario Nombre */
            usuario_nombre: string;
            /** Rol */
            rol?: string | null;
            /** Documento Id */
            documento_id: string;
            /** Documento Nombre */
            documento_nombre: string;
            /** Analisis Id */
            analisis_id: string;
            /** Hallazgo Id */
            hallazgo_id: string;
            /** Hallazgo Descripcion */
            hallazgo_descripcion: string;
            /** Resultado */
            resultado: string;
            /** Comentario */
            comentario?: string | null;
        };
        /** BitacoraEsquema */
        BitacoraEsquema: {
            /** Id */
            id: string;
            /** Accion */
            accion: string;
            /**
             * Fecha Hora
             * Format: date-time
             */
            fecha_hora: string;
            /** Detalle */
            detalle?: string | null;
        };
        /** Body_crear_fuente_curaduria_fuentes_post */
        Body_crear_fuente_curaduria_fuentes_post: {
            /** Fuente Id */
            fuente_id: string;
            /** Titulo */
            titulo: string;
            /** Tipo */
            tipo: string;
            /** Version */
            version: string;
            /**
             * Vigente Desde
             * Format: date
             */
            vigente_desde: string;
            /** Dueno */
            dueno: string;
            /**
             * Archivo
             * Format: binary
             */
            archivo: string;
        };
        /** Body_importar_plantilla_endpoint_curaduria_plantilla_importar_post */
        Body_importar_plantilla_endpoint_curaduria_plantilla_importar_post: {
            /**
             * Archivo
             * Format: binary
             */
            archivo: string;
        };
        /** Body_validar_plantilla_endpoint_curaduria_plantilla_validar_post */
        Body_validar_plantilla_endpoint_curaduria_plantilla_validar_post: {
            /**
             * Archivo
             * Format: binary
             */
            archivo: string;
        };
        /** ErrorImportacionEsquema */
        ErrorImportacionEsquema: {
            /** Hoja */
            hoja: string;
            /** Fila */
            fila?: number | null;
            /** Columna */
            columna?: string | null;
            /** Mensaje */
            mensaje: string;
        };
        /** FragmentoVistaPreviaEsquema */
        FragmentoVistaPreviaEsquema: {
            /** Contenido */
            contenido: string;
            /** Seccion */
            seccion?: string | null;
            /** Pagina */
            pagina?: number | null;
        };
        /** FuenteConocimientoEsquema */
        FuenteConocimientoEsquema: {
            /** Id */
            id: string;
            /** Fuente Id */
            fuente_id: string;
            /** Titulo */
            titulo: string;
            /** Tipo */
            tipo: string;
            /** Version */
            version: string;
            /**
             * Vigente Desde
             * Format: date
             */
            vigente_desde: string;
        };
        /** FuenteCuraduriaEsquema */
        FuenteCuraduriaEsquema: {
            /** Id */
            id: string;
            /** Fuente Id */
            fuente_id: string;
            /** Titulo */
            titulo: string;
            /** Tipo */
            tipo: string;
            /** Prioridad */
            prioridad: number;
            /** Version */
            version: string;
            /**
             * Vigente Desde
             * Format: date
             */
            vigente_desde: string;
            /** Estado */
            estado: string;
            /** Area Id */
            area_id: string;
            /** Dueno */
            dueno: string;
            /** Archivo */
            archivo: string;
            /** Sha256 */
            sha256?: string | null;
            /** Cargado Por */
            cargado_por: string;
            /** Aprobado Por */
            aprobado_por?: string | null;
            /**
             * Fecha Carga
             * Format: date-time
             */
            fecha_carga: string;
            /** Fecha Aprobacion */
            fecha_aprobacion?: string | null;
        };
        /** GlosarioEsquema */
        GlosarioEsquema: {
            /** Id */
            id: string;
            /** Termino */
            termino: string;
            /** Definicion */
            definicion: string;
            /** Area Id */
            area_id: string;
            /** Fuente Id */
            fuente_id?: string | null;
            /** Version */
            version?: string | null;
            /** Vigente Desde */
            vigente_desde?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HallazgoEsquema */
        HallazgoEsquema: {
            /** Id */
            id: string;
            /** Regla Codigo */
            regla_codigo?: string | null;
            /** Severidad */
            severidad: string;
            /** Ubicacion */
            ubicacion: string;
            /** Descripcion */
            descripcion: string;
            /** Correccion Sugerida */
            correccion_sugerida?: string | null;
            /** Monto */
            monto?: number | null;
            /** Moneda */
            moneda?: string | null;
            /** Estado */
            estado: string;
            /** Fuente Citada */
            fuente_citada?: string | null;
            /** Referencia Citada */
            referencia_citada?: string | null;
        };
        /** ParteSubidaEsquema */
        ParteSubidaEsquema: {
            /** Numero Parte */
            numero_parte: number;
            /** Etag */
            etag: string;
        };
        /** RespuestaAnalisis */
        RespuestaAnalisis: {
            /** Id */
            id: string;
            /** Documento Id */
            documento_id: string;
            /** Nombre Documento */
            nombre_documento?: string | null;
            /** Tipo Revision */
            tipo_revision: string;
            /** Estado */
            estado: string;
            /**
             * Fecha Inicio
             * Format: date-time
             */
            fecha_inicio: string;
            /** Fecha Fin */
            fecha_fin?: string | null;
            /** Periodo Cierre */
            periodo_cierre?: string | null;
            /** Total Debe */
            total_debe?: number | null;
            /** Total Haber */
            total_haber?: number | null;
            /** Moneda */
            moneda?: string | null;
            /**
             * Puede Decidir
             * @default false
             */
            puede_decidir: boolean;
            /**
             * Tiene Version Corregida
             * @default false
             */
            tiene_version_corregida: boolean;
        };
        /** RespuestaAprobarFuente */
        RespuestaAprobarFuente: {
            /** Fuente Id */
            fuente_id: string;
            /** Version */
            version: string;
            /** Fragmentos Indexados */
            fragmentos_indexados: number;
            /** Duracion Segundos */
            duracion_segundos: number;
            /** Version Anterior Obsoleta */
            version_anterior_obsoleta: boolean;
        };
        /** RespuestaCompletarCarga */
        RespuestaCompletarCarga: {
            /** Documento Id */
            documento_id: string;
            /** Analisis Id */
            analisis_id: string;
            /** Estado */
            estado: string;
        };
        /** RespuestaDecision */
        RespuestaDecision: {
            /** Id */
            id: string;
            /** Hallazgo Id */
            hallazgo_id: string;
            /** Resultado */
            resultado: string;
            /**
             * Fecha
             * Format: date-time
             */
            fecha: string;
        };
        /** RespuestaGenerarCorregido */
        RespuestaGenerarCorregido: {
            /** Generado */
            generado: boolean;
        };
        /** RespuestaImportarPlantilla */
        RespuestaImportarPlantilla: {
            /** Es Valido */
            es_valido: boolean;
            /** Errores */
            errores: components["schemas"]["ErrorImportacionEsquema"][];
            /** Cargado */
            cargado?: {
                [key: string]: number;
            } | null;
        };
        /** RespuestaIniciarCarga */
        RespuestaIniciarCarga: {
            /** Documento Id */
            documento_id: string;
            /** Upload Id */
            upload_id: string;
            /** Llave Almacenamiento */
            llave_almacenamiento: string;
        };
        /** RespuestaToken */
        RespuestaToken: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Rol */
            rol: string;
        };
        /** RespuestaValidarPlantilla */
        RespuestaValidarPlantilla: {
            /** Es Valido */
            es_valido: boolean;
            /** Errores */
            errores: components["schemas"]["ErrorImportacionEsquema"][];
            /** Resumen */
            resumen: {
                [key: string]: number;
            };
        };
        /** RespuestaVistaPrevia */
        RespuestaVistaPrevia: {
            /** Fragmentos */
            fragmentos: components["schemas"]["FragmentoVistaPreviaEsquema"][];
        };
        /** SolicitudCompletarCarga */
        SolicitudCompletarCarga: {
            /** Partes */
            partes: components["schemas"]["ParteSubidaEsquema"][];
            /** Tipo Revision */
            tipo_revision: string;
            /** Periodo Cierre */
            periodo_cierre?: string | null;
            /** Tipo Documento */
            tipo_documento?: string | null;
            /** Accion */
            accion?: string | null;
        };
        /** SolicitudDecision */
        SolicitudDecision: {
            /** Resultado */
            resultado: string;
            /** Comentario */
            comentario?: string | null;
        };
        /** SolicitudGlosario */
        SolicitudGlosario: {
            /** Termino */
            termino: string;
            /** Definicion */
            definicion: string;
        };
        /** SolicitudIniciarCarga */
        SolicitudIniciarCarga: {
            /** Nombre Original */
            nombre_original: string;
            /** Tipo Archivo */
            tipo_archivo: string;
            /** Tamano Bytes */
            tamano_bytes: number;
        };
        /** SolicitudLogin */
        SolicitudLogin: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    iniciar_carga_documentos_iniciar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudIniciarCarga"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaIniciarCarga"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subir_parte_documento_documentos__documento_id__partes__numero_parte__put: {
        parameters: {
            query: {
                upload_id: string;
                llave_almacenamiento: string;
            };
            header?: never;
            path: {
                documento_id: string;
                numero_parte: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_partes_subidas_documento_documentos__documento_id__partes_get: {
        parameters: {
            query: {
                upload_id: string;
                llave_almacenamiento: string;
            };
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParteSubidaEsquema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    completar_carga_documentos__documento_id__completar_post: {
        parameters: {
            query: {
                upload_id: string;
                llave_almacenamiento: string;
            };
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudCompletarCarga"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaCompletarCarga"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_analisis_analisis_get: {
        parameters: {
            query?: {
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaAnalisis"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consultar_analisis_analisis__analisis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analisis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaAnalisis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_hallazgos_analisis__analisis_id__hallazgos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analisis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallazgoEsquema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mejorar_redaccion_stream_analisis__analisis_id__mejorar_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analisis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_bitacora_analisis_analisis__analisis_id__bitacora_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analisis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BitacoraEsquema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decidir_hallazgo_hallazgos__hallazgo_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hallazgo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaDecision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generar_corregido_analisis__analisis_id__generar_corregido_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analisis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaGenerarCorregido"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_ajustes_autoaprobados_reportes_ajustes_autoaprobados_get: {
        parameters: {
            query?: {
                fecha_desde?: string | null;
                fecha_hasta?: string | null;
                usuario_email?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AjusteAutoaprobadoEsquema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_fuentes_conocimiento_fuentes_conocimiento_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FuenteConocimientoEsquema"][];
                };
            };
        };
    };
    descargar_version_corregida_documentos__documento_id__version_corregida_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_fuentes_curaduria_curaduria_fuentes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FuenteCuraduriaEsquema"][];
                };
            };
        };
    };
    crear_fuente_curaduria_fuentes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_crear_fuente_curaduria_fuentes_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FuenteCuraduriaEsquema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vista_previa_fuente_curaduria_fuentes__fuente_id__vista_previa_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fuente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaVistaPrevia"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aprobar_fuente_endpoint_curaduria_fuentes__fuente_id__aprobar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fuente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaAprobarFuente"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    marcar_fuente_obsoleta_curaduria_fuentes__fuente_id__marcar_obsoleta_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fuente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FuenteCuraduriaEsquema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_glosario_curaduria_curaduria_glosario_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlosarioEsquema"][];
                };
            };
        };
    };
    crear_termino_glosario_curaduria_glosario_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudGlosario"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlosarioEsquema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_termino_glosario_curaduria_glosario__termino_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                termino_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validar_plantilla_endpoint_curaduria_plantilla_validar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_validar_plantilla_endpoint_curaduria_plantilla_validar_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaValidarPlantilla"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    importar_plantilla_endpoint_curaduria_plantilla_importar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_importar_plantilla_endpoint_curaduria_plantilla_importar_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaImportarPlantilla"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
