/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/iniciar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar Carga */
        post: operations["iniciar_carga_documentos_iniciar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/partes/{numero_parte}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Subir Parte Documento */
        put: operations["subir_parte_documento_documentos__documento_id__partes__numero_parte__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento_id}/completar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Completar Carga */
        post: operations["completar_carga_documentos__documento_id__completar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analisis/{analisis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar Analisis */
        get: operations["consultar_analisis_analisis__analisis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analisis/{analisis_id}/hallazgos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Hallazgos */
        get: operations["listar_hallazgos_analisis__analisis_id__hallazgos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hallazgos/{hallazgo_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decidir Hallazgo */
        post: operations["decidir_hallazgo_hallazgos__hallazgo_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HallazgoEsquema */
        HallazgoEsquema: {
            /** Id */
            id: string;
            /** Regla Codigo */
            regla_codigo?: string | null;
            /** Severidad */
            severidad: string;
            /** Ubicacion */
            ubicacion: string;
            /** Descripcion */
            descripcion: string;
            /** Correccion Sugerida */
            correccion_sugerida?: string | null;
            /** Monto */
            monto?: number | null;
            /** Moneda */
            moneda?: string | null;
            /** Estado */
            estado: string;
        };
        /** ParteSubidaEsquema */
        ParteSubidaEsquema: {
            /** Numero Parte */
            numero_parte: number;
            /** Etag */
            etag: string;
        };
        /** RespuestaAnalisis */
        RespuestaAnalisis: {
            /** Id */
            id: string;
            /** Documento Id */
            documento_id: string;
            /** Tipo Revision */
            tipo_revision: string;
            /** Estado */
            estado: string;
            /**
             * Fecha Inicio
             * Format: date-time
             */
            fecha_inicio: string;
            /** Fecha Fin */
            fecha_fin?: string | null;
            /** Periodo Cierre */
            periodo_cierre?: string | null;
        };
        /** RespuestaCompletarCarga */
        RespuestaCompletarCarga: {
            /** Documento Id */
            documento_id: string;
            /** Analisis Id */
            analisis_id: string;
            /** Estado */
            estado: string;
        };
        /** RespuestaDecision */
        RespuestaDecision: {
            /** Id */
            id: string;
            /** Hallazgo Id */
            hallazgo_id: string;
            /** Resultado */
            resultado: string;
            /**
             * Fecha
             * Format: date-time
             */
            fecha: string;
        };
        /** RespuestaIniciarCarga */
        RespuestaIniciarCarga: {
            /** Documento Id */
            documento_id: string;
            /** Upload Id */
            upload_id: string;
            /** Llave Almacenamiento */
            llave_almacenamiento: string;
        };
        /** RespuestaToken */
        RespuestaToken: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Rol */
            rol: string;
        };
        /** SolicitudCompletarCarga */
        SolicitudCompletarCarga: {
            /** Partes */
            partes: components["schemas"]["ParteSubidaEsquema"][];
            /** Tipo Revision */
            tipo_revision: string;
            /** Periodo Cierre */
            periodo_cierre: string;
        };
        /** SolicitudDecision */
        SolicitudDecision: {
            /** Resultado */
            resultado: string;
            /** Comentario */
            comentario?: string | null;
        };
        /** SolicitudIniciarCarga */
        SolicitudIniciarCarga: {
            /** Nombre Original */
            nombre_original: string;
            /** Tipo Archivo */
            tipo_archivo: string;
            /** Tamano Bytes */
            tamano_bytes: number;
        };
        /** SolicitudLogin */
        SolicitudLogin: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    iniciar_carga_documentos_iniciar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudIniciarCarga"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaIniciarCarga"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subir_parte_documento_documentos__documento_id__partes__numero_parte__put: {
        parameters: {
            query: {
                upload_id: string;
                llave_almacenamiento: string;
            };
            header?: never;
            path: {
                documento_id: string;
                numero_parte: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    completar_carga_documentos__documento_id__completar_post: {
        parameters: {
            query: {
                upload_id: string;
                llave_almacenamiento: string;
            };
            header?: never;
            path: {
                documento_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudCompletarCarga"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaCompletarCarga"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consultar_analisis_analisis__analisis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analisis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaAnalisis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_hallazgos_analisis__analisis_id__hallazgos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analisis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallazgoEsquema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decidir_hallazgo_hallazgos__hallazgo_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hallazgo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaDecision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
